config/routes.rb
Rails.application.routes.draw do
root :to => "homes#top"
resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update]

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end


  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    redirect_to book_path(@book.id), notice: "Book was successfully created." 
    elsif 
      @books = Book.all
      render :index
    end
  end



  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if    @book.update(book_params)
          redirect_to book_path(@book.id), notice: "Book was successfully updated." 
 
    elsif
    render :edit
    end
  end

def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to "/books"
end


  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/_list.html.erb
<h1 class="index-hed">Books</h1>
<table>
  <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th> </th>
      </tr>
  </thead>  

<% @books.each do |book| %>
<tbody>
      <tr>
　        <td><%=  book.title %></td>
　        <td><%=  book.body %></td>
　        <td><%= link_to "Show", book_path(book) %></td>
　        <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>  
     </tr>
     <%end%>
  </tbody>
</table>



<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<h1>New book</h1>
<%= form_with model: @book do |f| %>

<div class=" new-title">
<p>Title</p>
<%= f.text_field :title %>
</div>

<div class= "new-body"> 
<p>Body</p>
<%= f.text_area :body %>
</div>

<%= f.submit "CreateBook" %>
<%end%>

app/views/books/edit.html.erb
<!--titleとbodyに空白があればエラーを表示（※正常に動作）-->

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>




<!--編集ページ（正常に動作）-->

<h1>Editing Book</h1>
<%= form_with model: @book do  |f| %>

<div class=edit-body>
<h4>Title</h4>
<%= f.text_field :title %>
<div>

<div class=edit-body>
<h4>Body</h4>
<%= f.text_field :body %>
</div>



<%= f.submit "Update Book" %></br>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>
<%end%>

app/views/books/index.html.erb
<h1 class="index-hed">Books</h1>
<table>
  <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th> </th>
      </tr>
  </thead>

<!--投稿一覧ページ（正常に動作）-->
<% @books.each do |book| %>
<tbody>
      <tr>
　        <td><%=  book.title %></td>
　        <td><%=  book.body %></td>
　        <td><%= link_to "Show", book_path(book) %></td>
　        <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
     </tr>
     <%end%>
  </tbody>
</table>





<!--titleとbodyに空白があればエラーを表示（正常に動作）-->

    <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<!--投稿作成ページ（正常に動作）-->
<h1>New book</h1>
<%= form_with model: @book do |f| %>
<div class=" new-title">
<p>Title</p>
<%= f.text_field :title %>
</div>

<div class= "new-body">
<p>Body</p>
<%= f.text_area :body %>
</div>

<%= f.submit "Create Book" %>
<%end%>

app/views/books/new.html.erb
投稿作成ページ（正常に動作）
<h1>投稿ページ</h1>
<%= form_with model: @book do |f| %>

<div class=" new-title">
<p>タイトル</p>
<%= f.text_field :title %>
</div>

<div class= "new-body"> 
<p>本文</p>
<%= f.text_area :body %>
</div>

<%= f.submit "投稿" %>
<%end%>

app/views/books/show.html.erb
<!--詳細ページ（正常に）-->

<div class= show-body>
<P><strong>title:</strong>
<%= @book.title %>
</P>

<p><strong>body:</strong>
<%= @book.body %>
</p>



<br><%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<div class=top-body>
<h1 class="top-title">ようこそ<span> Bookers</span> へ！</h1>
<p class= "top-text"><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>

<p class= "top-text">印象を共有し交換することができます</p>
<a href="/books" class="top-start">start </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--フラッシュメッセージ(notice)を追加　controllerのcreateとupdateアクションに結び付けている-->
<%= notice %>

    <%= yield %>
  </body>
</html>